SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_PlanCuentas_Insert
	@Codigo VARCHAR(15) = NULL,
	@Descripcion VARCHAR(255) = NULL
AS
BEGIN
SET NOCOUNT ON;
	BEGIN TRY
		BEGIN
			INSERT INTO PlanCuentas(Codigo, Descripcion)
			    VALUES(@Codigo, @Descripcion)
			        SELECT SCOPE_IDENTITY() AS IdPlanCuenta;
		END
	END TRY
	BEGIN CATCH
	SELECT ERROR_MESSAGE() AS ERROR,
				ERROR_NUMBER() AS ERROR_NRO
	END CATCH;
END
GO