SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_PeriodoContable_Insert
	@Inicio VARCHAR(155) = NULL,
    @Fin VARCHAR(155) = NULL,
	@Descripcion VARCHAR(255) = NULL
AS
BEGIN
SET NOCOUNT ON;
	BEGIN TRY
		BEGIN
			INSERT INTO PeriodosContables(Inicio, Fin, Descripcion)
			    VALUES(CONVERT(DATETIME, @Inicio, 103), CONVERT(DATETIME, @Fin, 103), @Descripcion)
			        SELECT SCOPE_IDENTITY() AS IdPeriodoContable;
		END
	END TRY
	BEGIN CATCH
	SELECT ERROR_MESSAGE() AS ERROR,
				ERROR_NUMBER() AS ERROR_NRO
	END CATCH;
END
GO